# arxivの学問領域の指定
subject: 'cat:astro-ph.EP OR cat:astro-ph.HE OR cat:astro-ph.SR'

# 検索キーワード
keywords:
        magnetic field: 1
        magnetic flux: 1
        planet formation: 1
        protoplanetary disk: 1
        JWST: 1
        VSI: 1
   
# 通知の閾値
score_threshold: 2
